# @package _global_
name: typed_code2seq

dataset:
  name: java-small-psi
  target:
    max_parts: 7
    is_wrapped: true
    is_splitted: true
    vocabulary_size: 11316
  token:
    max_parts: 5
    is_wrapped: false
    is_splitted: true
    vocabulary_size: 73904
  path:
    max_parts: 9
    is_wrapped: false
    is_splitted: true
    vocabulary_size: null
  type:
    max_parts: 5
    is_wrapped: false
    is_splitted: true
    vocabulary_size: null

encoder:
  embedding_size: 128
  rnn_size: 128
  use_bi_rnn: true
  embedding_dropout: 0.25
  rnn_num_layers: 1
  rnn_dropout: 0.5

decoder:
  decoder_size: 320
  embedding_size: 128
  num_decoder_layers: 1
  rnn_dropout: 0.5
  teacher_forcing: 1
  beam_width: 0
