# @package _global_
defaults:
  - model: code2seq

seed: 7
num_workers: 0
log_offline: false

# data keys
data_folder: data
vocabulary_name: vocabulary.pkl
train_holdout: train
val_holdout: val
test_holdout: test

save_every_epoch: 1
val_every_epoch: 1
log_every_epoch: 10
